/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.UI;
import commands.ExtendCommand;
import exceptions.CommandNotFoundException;
import factory.CommandFactory;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import manager.Executor;
import model.Note;

/**
 *
 * @author MarkLester
 */
public class ExtendSched extends javax.swing.JFrame implements UI {
    private Note note;
    /**
     * Creates new form ExtendSched
     */
    public ExtendSched(Note n) {
        initComponents();
        note = n;
        Executor.put(ExtendCommand.class, CommandFactory.createExtendCommand(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OKButton = new javax.swing.JPanel();
        NI12 = new javax.swing.JLabel();
        NI4 = new javax.swing.JLabel();
        DaysExtend = new javax.swing.JSpinner();
        HoursExtend = new javax.swing.JSpinner();
        NI1 = new javax.swing.JLabel();
        NI2 = new javax.swing.JLabel();
        MinExtend = new javax.swing.JSpinner();
        NI3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        OKButton.setBackground(new java.awt.Color(0, 102, 51));
        OKButton.setForeground(new java.awt.Color(204, 255, 204));
        OKButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKButton.setName("OKButton"); // NOI18N
        OKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OKButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OKButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OKButtonMouseExited(evt);
            }
        });

        NI12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        NI12.setForeground(new java.awt.Color(255, 255, 255));
        NI12.setText("OK");
        NI12.setName("NI12"); // NOI18N
        NI12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NI12FocusGained(evt);
            }
        });

        javax.swing.GroupLayout OKButtonLayout = new javax.swing.GroupLayout(OKButton);
        OKButton.setLayout(OKButtonLayout);
        OKButtonLayout.setHorizontalGroup(
            OKButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OKButtonLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(NI12)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        OKButtonLayout.setVerticalGroup(
            OKButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NI12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        NI4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NI4.setText("Extend task by :");
        NI4.setName("NI4"); // NOI18N

        DaysExtend.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        DaysExtend.setName("DaysExtend"); // NOI18N

        HoursExtend.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        HoursExtend.setName("HoursExtend"); // NOI18N

        NI1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NI1.setText("DAYS");
        NI1.setName("NI1"); // NOI18N

        NI2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NI2.setText("HOURS");
        NI2.setName("NI2"); // NOI18N

        MinExtend.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        MinExtend.setName("MinExtend"); // NOI18N

        NI3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NI3.setText("MINS");
        NI3.setName("NI3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NI4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DaysExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NI1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HoursExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NI2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NI3)
                        .addGap(0, 27, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(NI4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DaysExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NI1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoursExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NI2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(MinExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NI3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NI12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NI12FocusGained

    }//GEN-LAST:event_NI12FocusGained

    private void OKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseClicked
        try {
            Executor.execute(ExtendCommand.class);
        } catch (CommandNotFoundException ex) {
            Logger.getLogger(ExtendSched.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_OKButtonMouseClicked

    private void OKButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseEntered

    }//GEN-LAST:event_OKButtonMouseEntered

    private void OKButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OKButtonMouseExited

    }//GEN-LAST:event_OKButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner DaysExtend;
    private javax.swing.JSpinner HoursExtend;
    private javax.swing.JSpinner MinExtend;
    private javax.swing.JLabel NI1;
    private javax.swing.JLabel NI12;
    private javax.swing.JLabel NI2;
    private javax.swing.JLabel NI3;
    private javax.swing.JLabel NI4;
    private javax.swing.JPanel OKButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        Map fields = new HashMap();
        fields.put(DaysExtend.getName(), DaysExtend);
        fields.put(HoursExtend.getName(), HoursExtend);
        fields.put(MinExtend.getName(), MinExtend);
        fields.put("note", note);
        return fields;
    }
}
