/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.UI;
import commands.UpdateInterfaceCommand;
import exceptions.CommandNotFoundException;
import factory.CommandFactory;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import manager.Executor;

/**
 *
 * @author MarkLester
 */
public class MainWindow extends javax.swing.JFrame implements UI {
    private JFrame add_window;
    private JFrame ExtendWindow;
    private JFrame xp;    

    /**
     * Creates new form MainWindow
     */
    public MainWindow() throws InstantiationException, IllegalAccessException, CommandNotFoundException {
        initComponents();
        Executor.put(UpdateInterfaceCommand.class, CommandFactory.createUpdateInterfaceCommand(this));
        add_window = new Add_window();
        Executor.execute(UpdateInterfaceCommand.class);
        ExtendWindow = new ExtendWarning();
        xp = new EarnXP();
        SwingUtilities.invokeLater(
                new Runnable() {
                    public void run() {
                        try {
                            Executor.execute(UpdateInterfaceCommand.class);
                        } catch (CommandNotFoundException ex) {
                            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTitle = new javax.swing.JLabel();
        mainTab = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        Tiles_Container = new javax.swing.JPanel();
        heyTile = new javax.swing.JPanel();
        NI2 = new javax.swing.JLabel();
        TodayIsWhat = new javax.swing.JLabel();
        todayTile = new javax.swing.JPanel();
        DateOnTile = new javax.swing.JLabel();
        NI1 = new javax.swing.JLabel();
        TaskTodayCount = new javax.swing.JLabel();
        accomplishedTile = new javax.swing.JPanel();
        NI3 = new javax.swing.JLabel();
        AccomplishedTodayCount = new javax.swing.JLabel();
        NI4 = new javax.swing.JLabel();
        levelTile = new javax.swing.JPanel();
        NI23 = new javax.swing.JLabel();
        TaskingLevel = new javax.swing.JLabel();
        Upcoming_Container = new javax.swing.JPanel();
        Upcoming1Panel = new javax.swing.JPanel();
        Upcoming1Title = new javax.swing.JLabel();
        Upcoming1Accent = new javax.swing.JPanel();
        Upcoming1Sched = new javax.swing.JLabel();
        Upcoming2Panel = new javax.swing.JPanel();
        Upcoming2Title = new javax.swing.JLabel();
        Upcoming2Accent = new javax.swing.JPanel();
        Upcoming2Sched = new javax.swing.JLabel();
        Upcoming3Panel = new javax.swing.JPanel();
        Upcoming3Title = new javax.swing.JLabel();
        Upcoming3Accent = new javax.swing.JPanel();
        Upcoming3Sched = new javax.swing.JLabel();
        NI6 = new javax.swing.JLabel();
        Upcoming_See_All_Button = new javax.swing.JPanel();
        NI7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        todayTab = new javax.swing.JPanel();
        TaskListBox1 = new javax.swing.JScrollPane();
        TaskList1 = new javax.swing.JList();
        TaskTitle1 = new javax.swing.JLabel();
        NI8 = new javax.swing.JLabel();
        NI9 = new javax.swing.JLabel();
        NI10 = new javax.swing.JLabel();
        NI11 = new javax.swing.JLabel();
        NI12 = new javax.swing.JLabel();
        DescriptionBox1 = new javax.swing.JScrollPane();
        Description1 = new javax.swing.JTextArea();
        TaskSched1 = new javax.swing.JLabel();
        TaskDuration1 = new javax.swing.JLabel();
        AccomplishedYesNo1 = new javax.swing.JLabel();
        ExtendButton1 = new javax.swing.JLabel();
        DeleteButton1 = new javax.swing.JLabel();
        AccomplishButton1 = new javax.swing.JLabel();
        all_tasksTab = new javax.swing.JPanel();
        TaskListBox = new javax.swing.JScrollPane();
        TaskList = new javax.swing.JList();
        TaskTitle2 = new javax.swing.JLabel();
        NI13 = new javax.swing.JLabel();
        TaskSched2 = new javax.swing.JLabel();
        TaskDuration2 = new javax.swing.JLabel();
        NI14 = new javax.swing.JLabel();
        NI15 = new javax.swing.JLabel();
        AccomplishedYesNo2 = new javax.swing.JLabel();
        NI16 = new javax.swing.JLabel();
        NI17 = new javax.swing.JLabel();
        AccomplishButton2 = new javax.swing.JLabel();
        DeleteButton2 = new javax.swing.JLabel();
        DescriptionBox2 = new javax.swing.JScrollPane();
        Description2 = new javax.swing.JTextArea();
        ExtendButton2 = new javax.swing.JLabel();
        ProgramIcon = new javax.swing.JLabel();
        AddButton = new javax.swing.JLabel();
        NI20 = new javax.swing.JLabel();
        RunningTaskTitle = new javax.swing.JLabel();
        NI21 = new javax.swing.JLabel();
        NI22 = new javax.swing.JLabel();
        RankTop = new javax.swing.JLabel();
        NI24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        MainTitle.setBackground(new java.awt.Color(255, 255, 255));
        MainTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(0, 153, 153));
        MainTitle.setText("My Scheduler Pro");
        MainTitle.setName("MainTitle"); // NOI18N

        mainTab.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainTab.setName("mainTab"); // NOI18N

        homeTab.setName("homeTab"); // NOI18N

        Tiles_Container.setName("Tiles_Container"); // NOI18N

        heyTile.setBackground(new java.awt.Color(255, 0, 102));
        heyTile.setForeground(new java.awt.Color(204, 0, 153));
        heyTile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        heyTile.setName("heyTile"); // NOI18N

        NI2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NI2.setForeground(new java.awt.Color(255, 255, 255));
        NI2.setText("Hey! Welcome Back.");
        NI2.setName("NI2"); // NOI18N

        TodayIsWhat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TodayIsWhat.setForeground(new java.awt.Color(255, 255, 255));
        TodayIsWhat.setText("Today is Terrific Thursday.");
        TodayIsWhat.setName("TodayIsWhat"); // NOI18N

        javax.swing.GroupLayout heyTileLayout = new javax.swing.GroupLayout(heyTile);
        heyTile.setLayout(heyTileLayout);
        heyTileLayout.setHorizontalGroup(
            heyTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heyTileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(heyTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(heyTileLayout.createSequentialGroup()
                        .addComponent(TodayIsWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(NI2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        heyTileLayout.setVerticalGroup(
            heyTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heyTileLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(NI2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TodayIsWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        todayTile.setBackground(new java.awt.Color(0, 153, 102));
        todayTile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        todayTile.setName("todayTile"); // NOI18N
        todayTile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayTileMouseClicked(evt);
            }
        });

        DateOnTile.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DateOnTile.setForeground(new java.awt.Color(255, 255, 255));
        DateOnTile.setText("Dec 1, 2014");
        DateOnTile.setName("DateOnTile"); // NOI18N

        NI1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NI1.setForeground(new java.awt.Color(255, 255, 255));
        NI1.setText("Tasks");
        NI1.setName("NI1"); // NOI18N

        TaskTodayCount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TaskTodayCount.setForeground(new java.awt.Color(255, 255, 255));
        TaskTodayCount.setText("0");
        TaskTodayCount.setName("TaskTodayCount"); // NOI18N

        javax.swing.GroupLayout todayTileLayout = new javax.swing.GroupLayout(todayTile);
        todayTile.setLayout(todayTileLayout);
        todayTileLayout.setHorizontalGroup(
            todayTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayTileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(todayTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateOnTile, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(todayTileLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TaskTodayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NI1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        todayTileLayout.setVerticalGroup(
            todayTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayTileLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(DateOnTile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(todayTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaskTodayCount, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(NI1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        accomplishedTile.setBackground(new java.awt.Color(0, 153, 153));
        accomplishedTile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accomplishedTile.setName("accomplishedTile"); // NOI18N

        NI3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NI3.setForeground(new java.awt.Color(255, 255, 255));
        NI3.setText("Accomplished Today");
        NI3.setName("NI3"); // NOI18N

        AccomplishedTodayCount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AccomplishedTodayCount.setForeground(new java.awt.Color(255, 255, 255));
        AccomplishedTodayCount.setText("0");
        AccomplishedTodayCount.setName("AccomplishedTodayCount"); // NOI18N

        NI4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NI4.setForeground(new java.awt.Color(255, 255, 255));
        NI4.setText("Tasks");
        NI4.setName("NI4"); // NOI18N

        javax.swing.GroupLayout accomplishedTileLayout = new javax.swing.GroupLayout(accomplishedTile);
        accomplishedTile.setLayout(accomplishedTileLayout);
        accomplishedTileLayout.setHorizontalGroup(
            accomplishedTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accomplishedTileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NI3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(accomplishedTileLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(AccomplishedTodayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NI4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        accomplishedTileLayout.setVerticalGroup(
            accomplishedTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accomplishedTileLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(NI3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(accomplishedTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccomplishedTodayCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NI4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        levelTile.setBackground(new java.awt.Color(153, 0, 153));
        levelTile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        levelTile.setName("levelTile"); // NOI18N
        levelTile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelTileMouseClicked(evt);
            }
        });

        NI23.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        NI23.setForeground(new java.awt.Color(255, 255, 255));
        NI23.setText("Tasking Level");
        NI23.setName("NI23"); // NOI18N

        TaskingLevel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TaskingLevel.setForeground(new java.awt.Color(255, 255, 255));
        TaskingLevel.setText("Procrastinator");
        TaskingLevel.setName("TaskingLevel"); // NOI18N

        javax.swing.GroupLayout levelTileLayout = new javax.swing.GroupLayout(levelTile);
        levelTile.setLayout(levelTileLayout);
        levelTileLayout.setHorizontalGroup(
            levelTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelTileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(levelTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NI23, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaskingLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        levelTileLayout.setVerticalGroup(
            levelTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levelTileLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(NI23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaskingLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Tiles_ContainerLayout = new javax.swing.GroupLayout(Tiles_Container);
        Tiles_Container.setLayout(Tiles_ContainerLayout);
        Tiles_ContainerLayout.setHorizontalGroup(
            Tiles_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tiles_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tiles_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heyTile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Tiles_ContainerLayout.createSequentialGroup()
                        .addComponent(levelTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(Tiles_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(todayTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accomplishedTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Tiles_ContainerLayout.setVerticalGroup(
            Tiles_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tiles_ContainerLayout.createSequentialGroup()
                .addGroup(Tiles_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todayTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heyTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(Tiles_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelTile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accomplishedTile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Upcoming_Container.setName("Upcoming_Container"); // NOI18N

        Upcoming1Panel.setBackground(new java.awt.Color(204, 204, 204));
        Upcoming1Panel.setName("Upcoming1Panel"); // NOI18N

        Upcoming1Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Upcoming1Title.setName("Upcoming1Title"); // NOI18N

        Upcoming1Accent.setBackground(new java.awt.Color(0, 153, 102));
        Upcoming1Accent.setName("Upcoming1Accent"); // NOI18N

        javax.swing.GroupLayout Upcoming1AccentLayout = new javax.swing.GroupLayout(Upcoming1Accent);
        Upcoming1Accent.setLayout(Upcoming1AccentLayout);
        Upcoming1AccentLayout.setHorizontalGroup(
            Upcoming1AccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        Upcoming1AccentLayout.setVerticalGroup(
            Upcoming1AccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        Upcoming1Sched.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Upcoming1Sched.setName("Upcoming1Sched"); // NOI18N

        javax.swing.GroupLayout Upcoming1PanelLayout = new javax.swing.GroupLayout(Upcoming1Panel);
        Upcoming1Panel.setLayout(Upcoming1PanelLayout);
        Upcoming1PanelLayout.setHorizontalGroup(
            Upcoming1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upcoming1PanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Upcoming1Accent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Upcoming1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Upcoming1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upcoming1Sched, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Upcoming1PanelLayout.setVerticalGroup(
            Upcoming1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upcoming1PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Upcoming1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Upcoming1PanelLayout.createSequentialGroup()
                        .addComponent(Upcoming1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upcoming1Sched, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Upcoming1Accent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Upcoming2Panel.setBackground(new java.awt.Color(204, 204, 204));
        Upcoming2Panel.setName("Upcoming2Panel"); // NOI18N

        Upcoming2Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Upcoming2Title.setName("Upcoming2Title"); // NOI18N

        Upcoming2Accent.setBackground(new java.awt.Color(0, 153, 102));
        Upcoming2Accent.setName("Upcoming2Accent"); // NOI18N

        javax.swing.GroupLayout Upcoming2AccentLayout = new javax.swing.GroupLayout(Upcoming2Accent);
        Upcoming2Accent.setLayout(Upcoming2AccentLayout);
        Upcoming2AccentLayout.setHorizontalGroup(
            Upcoming2AccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        Upcoming2AccentLayout.setVerticalGroup(
            Upcoming2AccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        Upcoming2Sched.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Upcoming2Sched.setName("Upcoming2Sched"); // NOI18N

        javax.swing.GroupLayout Upcoming2PanelLayout = new javax.swing.GroupLayout(Upcoming2Panel);
        Upcoming2Panel.setLayout(Upcoming2PanelLayout);
        Upcoming2PanelLayout.setHorizontalGroup(
            Upcoming2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upcoming2PanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Upcoming2Accent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Upcoming2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Upcoming2Title, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upcoming2Sched, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Upcoming2PanelLayout.setVerticalGroup(
            Upcoming2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upcoming2PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Upcoming2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Upcoming2PanelLayout.createSequentialGroup()
                        .addComponent(Upcoming2Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upcoming2Sched, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Upcoming2Accent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Upcoming3Panel.setBackground(new java.awt.Color(204, 204, 204));
        Upcoming3Panel.setName("Upcoming3Panel"); // NOI18N

        Upcoming3Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Upcoming3Title.setName("Upcoming3Title"); // NOI18N

        Upcoming3Accent.setBackground(new java.awt.Color(0, 153, 102));
        Upcoming3Accent.setName("Upcoming3Accent"); // NOI18N

        javax.swing.GroupLayout Upcoming3AccentLayout = new javax.swing.GroupLayout(Upcoming3Accent);
        Upcoming3Accent.setLayout(Upcoming3AccentLayout);
        Upcoming3AccentLayout.setHorizontalGroup(
            Upcoming3AccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        Upcoming3AccentLayout.setVerticalGroup(
            Upcoming3AccentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        Upcoming3Sched.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Upcoming3Sched.setName("Upcoming3Sched"); // NOI18N

        javax.swing.GroupLayout Upcoming3PanelLayout = new javax.swing.GroupLayout(Upcoming3Panel);
        Upcoming3Panel.setLayout(Upcoming3PanelLayout);
        Upcoming3PanelLayout.setHorizontalGroup(
            Upcoming3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upcoming3PanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Upcoming3Accent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Upcoming3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Upcoming3Title, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Upcoming3Sched, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Upcoming3PanelLayout.setVerticalGroup(
            Upcoming3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upcoming3PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Upcoming3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Upcoming3PanelLayout.createSequentialGroup()
                        .addComponent(Upcoming3Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upcoming3Sched, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Upcoming3Accent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout Upcoming_ContainerLayout = new javax.swing.GroupLayout(Upcoming_Container);
        Upcoming_Container.setLayout(Upcoming_ContainerLayout);
        Upcoming_ContainerLayout.setHorizontalGroup(
            Upcoming_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upcoming_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Upcoming_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Upcoming1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Upcoming2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Upcoming3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Upcoming_ContainerLayout.setVerticalGroup(
            Upcoming_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upcoming_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Upcoming1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Upcoming2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Upcoming3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NI6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NI6.setText("Upcoming Today");
        NI6.setName("NI6"); // NOI18N

        Upcoming_See_All_Button.setBackground(new java.awt.Color(204, 204, 204));
        Upcoming_See_All_Button.setForeground(new java.awt.Color(204, 255, 204));
        Upcoming_See_All_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Upcoming_See_All_Button.setName("Upcoming_See_All_Button"); // NOI18N
        Upcoming_See_All_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Upcoming_See_All_ButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Upcoming_See_All_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Upcoming_See_All_ButtonMouseExited(evt);
            }
        });

        NI7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        NI7.setText("See all");
        NI7.setName("NI7"); // NOI18N
        NI7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NI7FocusGained(evt);
            }
        });

        javax.swing.GroupLayout Upcoming_See_All_ButtonLayout = new javax.swing.GroupLayout(Upcoming_See_All_Button);
        Upcoming_See_All_Button.setLayout(Upcoming_See_All_ButtonLayout);
        Upcoming_See_All_ButtonLayout.setHorizontalGroup(
            Upcoming_See_All_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upcoming_See_All_ButtonLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(NI7)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        Upcoming_See_All_ButtonLayout.setVerticalGroup(
            Upcoming_See_All_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NI7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/star.png"))); // NOI18N
        jLabel1.setText(" XP Points: ");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("250");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addComponent(Tiles_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeTabLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(NI6))
                            .addGroup(homeTabLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homeTabLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Upcoming_See_All_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Upcoming_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tiles_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addComponent(NI6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upcoming_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Upcoming_See_All_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainTab.addTab("  home    ", homeTab);

        todayTab.setName("todayTab"); // NOI18N

        TaskListBox1.setName("TaskListBox1"); // NOI18N

        TaskList1.setBackground(new java.awt.Color(240, 240, 240));
        TaskList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TaskList1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Task 1", "Task 2", "Task 3", "Task 4", "Task 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        TaskList1.setName("TaskList1"); // NOI18N
        TaskListBox1.setViewportView(TaskList1);

        TaskTitle1.setBackground(new java.awt.Color(0, 102, 102));
        TaskTitle1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        TaskTitle1.setText("Study CMSC 57");
        TaskTitle1.setName("TaskTitle1"); // NOI18N

        NI8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NI8.setText("*select a task from the list to see details");
        NI8.setName("NI8"); // NOI18N

        NI9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI9.setText("Scheduled Time:");
        NI9.setName("NI9"); // NOI18N

        NI10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI10.setText("Duration:");
        NI10.setName("NI10"); // NOI18N

        NI11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI11.setText("Accomplished?:");
        NI11.setName("NI11"); // NOI18N

        NI12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI12.setText("Description:");
        NI12.setName("NI12"); // NOI18N

        DescriptionBox1.setName("DescriptionBox1"); // NOI18N

        Description1.setBackground(new java.awt.Color(240, 240, 240));
        Description1.setColumns(20);
        Description1.setRows(5);
        Description1.setFocusable(false);
        Description1.setName("Description1"); // NOI18N
        DescriptionBox1.setViewportView(Description1);

        TaskSched1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskSched1.setText("12:00 PM - 1:00 PM");
        TaskSched1.setName("TaskSched1"); // NOI18N

        TaskDuration1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskDuration1.setText("1 Hour");
        TaskDuration1.setName("TaskDuration1"); // NOI18N

        AccomplishedYesNo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AccomplishedYesNo1.setText("No");
        AccomplishedYesNo1.setName("AccomplishedYesNo1"); // NOI18N

        ExtendButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ExtendButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/extend.png"))); // NOI18N
        ExtendButton1.setText("EXTEND");
        ExtendButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExtendButton1.setName("ExtendButton1"); // NOI18N
        ExtendButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExtendButton1MouseClicked(evt);
            }
        });

        DeleteButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        DeleteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_icon.png"))); // NOI18N
        DeleteButton1.setText("  DELETE");
        DeleteButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton1.setName("DeleteButton1"); // NOI18N

        AccomplishButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccomplishButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check_icon.png"))); // NOI18N
        AccomplishButton1.setText("ACCOMPLISH");
        AccomplishButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccomplishButton1.setName("AccomplishButton1"); // NOI18N
        AccomplishButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccomplishButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout todayTabLayout = new javax.swing.GroupLayout(todayTab);
        todayTab.setLayout(todayTabLayout);
        todayTabLayout.setHorizontalGroup(
            todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskListBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(todayTabLayout.createSequentialGroup()
                            .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NI8)
                                .addComponent(NI11)
                                .addComponent(NI12))
                            .addGap(74, 74, 74))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, todayTabLayout.createSequentialGroup()
                            .addComponent(NI10)
                            .addGap(133, 133, 133)
                            .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AccomplishedYesNo1)
                                .addComponent(TaskDuration1))))
                    .addComponent(TaskTitle1)
                    .addGroup(todayTabLayout.createSequentialGroup()
                        .addComponent(NI9)
                        .addGap(77, 77, 77)
                        .addComponent(TaskSched1))
                    .addComponent(DescriptionBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(todayTabLayout.createSequentialGroup()
                        .addComponent(AccomplishButton1)
                        .addGap(29, 29, 29)
                        .addComponent(DeleteButton1)
                        .addGap(45, 45, 45)
                        .addComponent(ExtendButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        todayTabLayout.setVerticalGroup(
            todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskListBox1)
                    .addGroup(todayTabLayout.createSequentialGroup()
                        .addComponent(TaskTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NI9)
                            .addComponent(TaskSched1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NI10)
                            .addComponent(TaskDuration1))
                        .addGap(11, 11, 11)
                        .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NI11)
                            .addComponent(AccomplishedYesNo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NI12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NI8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todayTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DeleteButton1)
                                .addComponent(ExtendButton1))
                            .addComponent(AccomplishButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        mainTab.addTab("  today    ", todayTab);

        all_tasksTab.setName("all_tasksTab"); // NOI18N

        TaskListBox.setName("TaskListBox"); // NOI18N

        TaskList.setBackground(new java.awt.Color(240, 240, 240));
        TaskList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TaskList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Task 1", "Task 2", "Task 3", "Task 4", "Task 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        TaskList.setName("TaskList"); // NOI18N
        TaskListBox.setViewportView(TaskList);

        TaskTitle2.setBackground(new java.awt.Color(0, 102, 102));
        TaskTitle2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        TaskTitle2.setText("Study CMSC 57");
        TaskTitle2.setName("TaskTitle2"); // NOI18N

        NI13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI13.setText("Scheduled Time:");
        NI13.setName("NI13"); // NOI18N

        TaskSched2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskSched2.setText("12:00 PM - 1:00 PM");
        TaskSched2.setName("TaskSched2"); // NOI18N

        TaskDuration2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaskDuration2.setText("1 Hour");
        TaskDuration2.setName("TaskDuration2"); // NOI18N

        NI14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI14.setText("Duration:");
        NI14.setName("NI14"); // NOI18N

        NI15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI15.setText("Accomplished?:");
        NI15.setName("NI15"); // NOI18N

        AccomplishedYesNo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AccomplishedYesNo2.setText("No");
        AccomplishedYesNo2.setName("AccomplishedYesNo2"); // NOI18N

        NI16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NI16.setText("Description:");
        NI16.setName("NI16"); // NOI18N

        NI17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NI17.setText("*select a task from the list to see details");
        NI17.setName("NI17"); // NOI18N

        AccomplishButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccomplishButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check_icon.png"))); // NOI18N
        AccomplishButton2.setText("ACCOMPLISH");
        AccomplishButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AccomplishButton2.setName("AccomplishButton2"); // NOI18N
        AccomplishButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccomplishButton2MouseClicked(evt);
            }
        });

        DeleteButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        DeleteButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_icon.png"))); // NOI18N
        DeleteButton2.setText("  DELETE");
        DeleteButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton2.setName("DeleteButton2"); // NOI18N

        DescriptionBox2.setName("DescriptionBox2"); // NOI18N

        Description2.setBackground(new java.awt.Color(240, 240, 240));
        Description2.setColumns(20);
        Description2.setRows(5);
        Description2.setFocusable(false);
        Description2.setName("Description2"); // NOI18N
        DescriptionBox2.setViewportView(Description2);

        ExtendButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ExtendButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/extend.png"))); // NOI18N
        ExtendButton2.setText("EXTEND");
        ExtendButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExtendButton2.setName("ExtendButton2"); // NOI18N
        ExtendButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExtendButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout all_tasksTabLayout = new javax.swing.GroupLayout(all_tasksTab);
        all_tasksTab.setLayout(all_tasksTabLayout);
        all_tasksTabLayout.setHorizontalGroup(
            all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_tasksTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(all_tasksTabLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(all_tasksTabLayout.createSequentialGroup()
                                    .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NI17)
                                        .addComponent(NI15)
                                        .addComponent(NI16))
                                    .addGap(74, 74, 74))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, all_tasksTabLayout.createSequentialGroup()
                                    .addComponent(NI14)
                                    .addGap(133, 133, 133)
                                    .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AccomplishedYesNo2)
                                        .addComponent(TaskDuration2))))
                            .addComponent(TaskTitle2)
                            .addGroup(all_tasksTabLayout.createSequentialGroup()
                                .addComponent(AccomplishButton2)
                                .addGap(29, 29, 29)
                                .addComponent(DeleteButton2)
                                .addGap(45, 45, 45)
                                .addComponent(ExtendButton2))
                            .addGroup(all_tasksTabLayout.createSequentialGroup()
                                .addComponent(NI13)
                                .addGap(77, 77, 77)
                                .addComponent(TaskSched2)))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, all_tasksTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DescriptionBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        all_tasksTabLayout.setVerticalGroup(
            all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_tasksTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(all_tasksTabLayout.createSequentialGroup()
                        .addComponent(TaskTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NI13)
                            .addComponent(TaskSched2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NI14)
                            .addComponent(TaskDuration2))
                        .addGap(11, 11, 11)
                        .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NI15)
                            .addComponent(AccomplishedYesNo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NI16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescriptionBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NI17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, all_tasksTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DeleteButton2)
                                .addComponent(ExtendButton2))
                            .addComponent(AccomplishButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(TaskListBox))
                .addContainerGap())
        );

        mainTab.addTab("  all tasks    ", all_tasksTab);

        ProgramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/software_icon.png"))); // NOI18N
        ProgramIcon.setName("ProgramIcon"); // NOI18N

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil_icon.png"))); // NOI18N
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.setName("AddButton"); // NOI18N
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        NI20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NI20.setText("Currently Running Task:");
        NI20.setName("NI20"); // NOI18N

        RunningTaskTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RunningTaskTitle.setText("Study CMSC 57");
        RunningTaskTitle.setName("RunningTaskTitle"); // NOI18N

        NI21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/running.png"))); // NOI18N
        NI21.setName("NI21"); // NOI18N

        NI22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NI22.setText("Rank:");
        NI22.setName("NI22"); // NOI18N

        RankTop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RankTop.setForeground(new java.awt.Color(153, 0, 0));
        RankTop.setText("Procrastinator!");
        RankTop.setName("RankTop"); // NOI18N

        NI24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ribbon.png"))); // NOI18N
        NI24.setName("NI24"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProgramIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(NI21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RunningTaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NI20, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NI24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RankTop, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NI22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(AddButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ProgramIcon)
                            .addComponent(AddButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NI20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NI22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(NI21)
                                .addComponent(NI24))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RunningTaskTitle)
                                .addComponent(RankTop)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void levelTileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelTileMouseClicked
        
    }//GEN-LAST:event_levelTileMouseClicked

    
    private void NI7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NI7FocusGained

    }//GEN-LAST:event_NI7FocusGained

    private void Upcoming_See_All_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Upcoming_See_All_ButtonMouseClicked
        mainTab.setSelectedIndex(1);
    }//GEN-LAST:event_Upcoming_See_All_ButtonMouseClicked

    private void Upcoming_See_All_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Upcoming_See_All_ButtonMouseEntered
        homeTab.setBackground(new java.awt.Color(190, 190, 190));
    }//GEN-LAST:event_Upcoming_See_All_ButtonMouseEntered

    private void Upcoming_See_All_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Upcoming_See_All_ButtonMouseExited
        homeTab.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_Upcoming_See_All_ButtonMouseExited

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        add_window.setVisible(true);
    }//GEN-LAST:event_AddButtonMouseClicked

    private void todayTileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayTileMouseClicked
        mainTab.setSelectedIndex(1);
    }//GEN-LAST:event_todayTileMouseClicked

    private void ExtendButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtendButton1MouseClicked
       ExtendWindow.setVisible(true);
    }//GEN-LAST:event_ExtendButton1MouseClicked

    private void ExtendButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtendButton2MouseClicked
        ExtendWindow.setVisible(true);
    }//GEN-LAST:event_ExtendButton2MouseClicked

    private void AccomplishButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccomplishButton1MouseClicked
        xp.setVisible(true);
    }//GEN-LAST:event_AccomplishButton1MouseClicked

    private void AccomplishButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccomplishButton2MouseClicked
        xp.setVisible(true);
    }//GEN-LAST:event_AccomplishButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccomplishButton1;
    private javax.swing.JLabel AccomplishButton2;
    private javax.swing.JLabel AccomplishedTodayCount;
    private javax.swing.JLabel AccomplishedYesNo1;
    private javax.swing.JLabel AccomplishedYesNo2;
    private javax.swing.JLabel AddButton;
    private javax.swing.JLabel DateOnTile;
    private javax.swing.JLabel DeleteButton1;
    private javax.swing.JLabel DeleteButton2;
    private javax.swing.JTextArea Description1;
    private javax.swing.JTextArea Description2;
    private javax.swing.JScrollPane DescriptionBox1;
    private javax.swing.JScrollPane DescriptionBox2;
    private javax.swing.JLabel ExtendButton1;
    private javax.swing.JLabel ExtendButton2;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel NI1;
    private javax.swing.JLabel NI10;
    private javax.swing.JLabel NI11;
    private javax.swing.JLabel NI12;
    private javax.swing.JLabel NI13;
    private javax.swing.JLabel NI14;
    private javax.swing.JLabel NI15;
    private javax.swing.JLabel NI16;
    private javax.swing.JLabel NI17;
    private javax.swing.JLabel NI2;
    private javax.swing.JLabel NI20;
    private javax.swing.JLabel NI21;
    private javax.swing.JLabel NI22;
    private javax.swing.JLabel NI23;
    private javax.swing.JLabel NI24;
    private javax.swing.JLabel NI3;
    private javax.swing.JLabel NI4;
    private javax.swing.JLabel NI6;
    private javax.swing.JLabel NI7;
    private javax.swing.JLabel NI8;
    private javax.swing.JLabel NI9;
    private javax.swing.JLabel ProgramIcon;
    private javax.swing.JLabel RankTop;
    private javax.swing.JLabel RunningTaskTitle;
    private javax.swing.JLabel TaskDuration1;
    private javax.swing.JLabel TaskDuration2;
    private javax.swing.JList TaskList;
    private javax.swing.JList TaskList1;
    private javax.swing.JScrollPane TaskListBox;
    private javax.swing.JScrollPane TaskListBox1;
    private javax.swing.JLabel TaskSched1;
    private javax.swing.JLabel TaskSched2;
    private javax.swing.JLabel TaskTitle1;
    private javax.swing.JLabel TaskTitle2;
    private javax.swing.JLabel TaskTodayCount;
    private javax.swing.JLabel TaskingLevel;
    private javax.swing.JPanel Tiles_Container;
    private javax.swing.JLabel TodayIsWhat;
    private javax.swing.JPanel Upcoming1Accent;
    private javax.swing.JPanel Upcoming1Panel;
    private javax.swing.JLabel Upcoming1Sched;
    private javax.swing.JLabel Upcoming1Title;
    private javax.swing.JPanel Upcoming2Accent;
    private javax.swing.JPanel Upcoming2Panel;
    private javax.swing.JLabel Upcoming2Sched;
    private javax.swing.JLabel Upcoming2Title;
    private javax.swing.JPanel Upcoming3Accent;
    private javax.swing.JPanel Upcoming3Panel;
    private javax.swing.JLabel Upcoming3Sched;
    private javax.swing.JLabel Upcoming3Title;
    private javax.swing.JPanel Upcoming_Container;
    private javax.swing.JPanel Upcoming_See_All_Button;
    private javax.swing.JPanel accomplishedTile;
    private javax.swing.JPanel all_tasksTab;
    private javax.swing.JPanel heyTile;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel levelTile;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JPanel todayTab;
    private javax.swing.JPanel todayTile;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        Map fields = new HashMap();
        
        fields.put(TaskTitle1.getName(), TaskTitle1);
        fields.put(TaskSched1.getName(), TaskSched1);
        fields.put(TaskDuration1.getName(), TaskDuration1);
        fields.put(AccomplishedYesNo1.getName(), AccomplishedYesNo1);
        fields.put(Description1.getName(),Description1);
        
        fields.put(TaskTitle2.getName(), TaskTitle2);
        fields.put(TaskSched2.getName(), TaskSched2);
        fields.put(TaskDuration2.getName(), TaskDuration2);
        fields.put(AccomplishedYesNo2.getName(), AccomplishedYesNo2);
        fields.put(Description2.getName(),Description2);
        
        fields.put(TaskList1.getName(), TaskList1);
        fields.put(RunningTaskTitle.getName(), RunningTaskTitle);
        
        fields.put(Upcoming1Title.getName(), Upcoming1Title);
        fields.put(Upcoming2Title.getName(), Upcoming2Title);
        fields.put(Upcoming3Title.getName(), Upcoming3Title);
        
        fields.put(Upcoming1Sched.getName(), Upcoming1Sched);
        fields.put(Upcoming2Sched.getName(), Upcoming2Sched);
        fields.put(Upcoming3Sched.getName(), Upcoming3Sched);
        
        fields.put(TodayIsWhat.getName(), TodayIsWhat);
        fields.put(TaskingLevel.getName(), TaskingLevel);    
        fields.put(TaskTodayCount.getName(), TaskTodayCount);
        fields.put(AccomplishedTodayCount.getName(), AccomplishedTodayCount);
        fields.put(RankTop.getName(), RankTop);
        
        return fields;
    }
    
}
